version: '3.8'
services:
  db:
    build: ../mini-db-engine
    healthcheck:
      test: ["CMD", "python", "-c", "import os; print(os.path.exists('data.db'))"]
      interval: 5s
      timeout: 3s
      retries: 3

  gateway:
    build: ../mini-api-gateway
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
